# Generated by Django 4.2.7 on 2025-09-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('home_garden', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('books', 'Books & Media'), ('health', 'Health & Beauty'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('art', 'Art & Collectibles'), ('digital', 'Digital Products'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
