# Generated by Django 4.2.7 on 2025-09-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_improve_price_currency_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
