# Generated by Django 4.2.7 on 2025-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_listing_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_method',
            field=models.CharField(choices=[('escrow', 'Using escrow'), ('direct', 'Direct')], default='escrow', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USDT', 'Tether USD'), ('USDC', 'USD Coin')], default='USDT', max_length=10),
        ),
    ]
