# Generated by Django 4.2.7 on 2025-09-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_delivery_add_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='arbitration_method',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='file_hash',
        ),
    ]
