# Generated by Django 4.2.7 on 2025-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_remove_arbitration_and_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
