# Generated by Django 4.2.7 on 2025-09-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
