# Generated by Django 4.2.7 on 2025-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_remove_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='access_duration_days',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_duration_days',
            field=models.IntegerField(default=30, help_text='Number of days the listing will be active'),
        ),
    ]
