# Generated by Django 4.2.7 on 2025-09-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_rename_access_duration_to_listing_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='requires_license_key',
        ),
    ]
