# Generated by Django 4.2.7 on 2025-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_remove_requires_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privy_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
